### PR TITLE
Update subscriber by email method added, some example additions done.

### PR DESCRIPTION
**Pull request by Ardakilic**
Hello,

We're using Mailwizz, and loving it so far! We're also using this very PHP client. However, we had a feature missing. It's a way to update a user's preferences by email method. By checking the source code, I saw it'd be fairly easy to implement this. So this is my humble attempt to implement a `updateByEmail` method. Also, the example PHP file was missing a `unsubscribeByEmailFromAllLists` example, so I've added that.

I hope this is considered for merging.

Thanks again for maintaining the project!

### CODE REVIEW

**Comment by twisted1919** [comment]
Awesome work, thank you!

**Comment by Ardakilic** [comment]
Hey @twisted1919 , thanks for the merge! Also, if not much, I'd appreciate if you could make a new release for this, because we're following tags as dependencies.

**Comment by twisted1919** [comment]
That makes sense. v1.0.6 has been released. Cheers.

**Comment by Ardakilic** [comment]
Awesome, thanks again for the merge and the release! 🎉

**Pull request merged**
